# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_conv <- function(x, y) {
    .Call(`_rpeaks_fast_conv`, x, y)
}

detect_peaks <- function(signal, lower_bound, refractory) {
    .Call(`_rpeaks_detect_peaks`, signal, lower_bound, refractory)
}

